### PR TITLE
Use debug instead of console.log

### PR DESCRIPTION
**Pull request by bonan**
Switches the package to using [debug](https://www.npmjs.com/package/debug) instead of writing directly to the console.

Debug output can be enabled by adding `DEBUG=node-coap-client` to the environment

### CODE REVIEW

**Comment by AlCalzone** [comment]
Thanks for the PR. I took a quick look over the package site on NPM. Do you know if I can also use this to intercept the debug output in other packages which require node-coap-client?

**Comment by bonan** [comment]
I don't see any way of doing that programmatically

**Comment by bonan** [comment]
Maybe a better solution would be to implement a simpler way to either redirect or discard output, something like:

```typescript
export declare type Logger = (message?: any, ...optionalParams: any[]) => void
```
and
```typescript
public setLogger(logger: Logger): void {
    CoapClient.log = logger;
}
```

And then call `CoapClient.log(...)` instead of `debug()` or `console.log()`.

`CoapClient.log` could by default be set to `console.log`

**Comment by AlCalzone** [comment]
merged in https://github.com/AlCalzone/node-coap-client/commit/c8f94bbaec0208ace1c5aa81f4c95ccf8853fa1a
closing PR

**Pull request closed without merging**
